name: PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      - name: Authenticate to Dev Hub
        env:
          SFDX_CLIENT_ID: ${{ secrets.SFDX_CONSUMERKEY }}
          SFDX_JWT_KEY_FILE: ${{ secrets.SFDX_SERVERKEY }}
          SFDX_USERNAME: ${{ secrets.SFDX_USERNAME }}
        run: sfdx auth:jwt:grant --clientid $SFDX_CONSUMERKEY --jwtkeyfile $SFDX_SERVERKEY --username $SFDX_USERNAME --instanceurl https://login.salesforce.com

      - name: Set API Version
        run: |
          sed -i 's/"sourceApiVersion": "[^"]*"/"sourceApiVersion": "60.0"/' sfdx-project.json
          cat sfdx-project.json

      - name: Validate code
        run: sfdx force:source:validate -x manifest/package.xml
