name: Create PR from dev to main

on:
  push:
    branches:
      - dev

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        id: create_pr
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT}}
          script: |
            const sourceBranch = 'dev';
            const targetBranch = 'main';
            const title = `PR from ${sourceBranch} to ${targetBranch}`;
            const body = 'PR from dev to main';

            const { data: pullRequest } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              head: sourceBranch,
              base: targetBranch,
              body: body,
            });

            console.log(`Pull request created: ${pullRequest.html_url}`);
